### ISSUE TITLE
NULL columns

### ISSUE THREAD

**Issue by ehnajafi** [martinrybak/SQLClient#16]
If a column has null values, the client will exit code and will report an error code.

I get columns number out of range for multiple columns. I tried the following queries:

SELECT \* FROM myTable; <======== Column out of range error

SELECT tableID FROM myTable <====== This worked.

SELECT tableID, name FROM myTable <======= Failed with Column out of range error  (There are no Null's in any of the columns.)

Is there a way around this issue?

Thanks,
Hamid

**Comment by martinrybak** [comment]
Please try out the `types` branch. This issue should be fixed.
