### ISSUE TITLE
Quick Question on Alerts

### ISSUE THREAD

**Issue by kylebshr** [martinrybak/SQLClient#18]
Hey there, 

In the app I'm using I have some custom alerts for when the app fails to connect, but there are also several errors that pop up from the SQLClient itself. I've browsed through most of the code and I can't find where they're coming from. What's the best to take those out/suppress them? Thank you!

Kyle

**Comment by martinrybak** [comment]
The only way `SQLClient` communicates errors are through the 2 `SQLClientDelegate` methods. They in turn get their errors from the underlying FreeTDS library. If you want to ignore some errors, your handler can examine their code or severity.
