### ISSUE TITLE
Don't want to use the SQLClient.sharedInstance

### ISSUE THREAD

**Issue by ronnycsharp** [martinrybak/SQLClient#22]
Hello Martin,
your project is really cool.
I am using it in my project with swift.
It works fine with one execution but I need a few executions parallel.
But it doesn't work. The app crashes. I need multiple instances of SQLClient
and I am instantiating a few SQLClient's and I do not use the sharedInstance.

The connection establishes and in the callback I am executing the sql statement with the
execute-method, and then it crashes.

libc++abi.dylib: terminating with uncaught exception of type NSException

With the sharedInstance it works.

Hope you can help.
Regards
Ronny

**Comment by martinrybak** [comment]
Currently `SQLClient` only supports one connection and one command at a time. FreeTDS might be able to support concurrent connections, meaning you could potentially execute multiple commands concurrently. I welcome a PR for this!
