### ISSUE TITLE
Loading binary data, truncated after 255 chars

### ISSUE THREAD

**Issue by ronnycsharp** [martinrybak/SQLClient#23]
Hi,
I need to load data from a table with a binary column.
Its defined as varbinary(max).  Its a pdf-document. (300kb-1mb).
The loaded row is truncated after 255 chars.

I ve created a stored proc on the server to split the data into many rows.
But thats a very bad way.

Is there another (better) way to do it?

Thank you.

ps.
I've also seen that I can load 8000 chars but the binary data will be converted to ascii.
And the strings will be truncated.

Regards
Ronny

**Comment by martinrybak** [comment]
Please try out the `types` branch. This issue should be fixed.
