### ISSUE TITLE
[!] The dependency `SQLClient (~> 0.1.3)` is not used in any concrete target.

### ISSUE THREAD

**Issue by kevlangdo** [martinrybak/SQLClient#28]
I ran the pod install from terminal as per the instructions.
At the end of the installation i am getting this output

Setting up CocoaPods master repo
Setup completed
Analyzing dependencies
[!] The dependency `SQLClient (~> 0.1.3)` is not used in any concrete target.

Is this an issue? is so what to do to fix

**Comment by azureskyline** [comment]
I also got that problem.

**Comment by cposton** [comment]
As of CocoaPods 1.0, you must now specify the target for all pods. Reference [The Podfile](https://guides.cocoapods.org/using/the-podfile.html) for examples and more information.
