### ISSUE TITLE
pulling text from varchar(MAX) column is truncated to 4096 characters

### ISSUE THREAD

**Issue by indieshack** [martinrybak/SQLClient#33]
I'm attempting to pull data from a varchar(MAX) column, but it truncates to 4096 characters - any idea what's happening?
thanks

**Comment by martinrybak** [comment]
Please use the `types` branch, it is a pre-1.0.0 release. The maximum length of a string in a query is configured on the server via the `SET TEXTSIZE` command. To find out your current setting, execute  `SELECT @@TEXTSIZE`. SQLClient uses `4096` by default. To override this, update its `maxTextSize` property.

**Comment by indieshack** [comment]
Thanks for the fast reply. I changed out the SQLClient code in my project for the "types" branch but now get the following linking on compile for testing on a sim:

Undefined symbols for architecture x86_64:
  "_dbanydatecrack", referenced from:
      ___32-[SQLClient execute:completion:]_block_invoke in SQLClient.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by martinrybak** [comment]
You need to update to update the `libsybdb.a` file as well.

**Comment by indieshack** [comment]
Thanks - looks like this branch can't make simultaneous connections?

**Comment by martinrybak** [comment]
Simultaneous connections were never supported.

**Comment by indieshack** [comment]
Thanks Martin, then I'm looking at some other change in behavior from an earlier version. Appreciate your fast response.

**Comment by martinrybak** [comment]
Yes, the API is a little different and I fixed a lot of bugs and added proper type handling. Please run the integration test suite against your SQL Server to make sure everything works. Instructions are in the readme.

**Comment by indieshack** [comment]
Appreciate your work on this - it's been a lifesaver :)

**Comment by martinrybak** [comment]
Thanks! Glad you found it useful.
