### ISSUE TITLE
Swift and SQLClient

### ISSUE THREAD

**Issue by Adonis640320** [martinrybak/SQLClient#34]
Hi, I've tried to use **SQLClient** in **Swift** project.
But I can not include **SQLClient.h**.
Please provide the way how to use this in **Swift** project.

Thanks

Adonis

**Comment by bhatti-saqib** [comment]
Use cocoa pods to install SQLClient. And then simply write import statement where you want to use it

#import SQLClient

**Comment by Adonis640320** [comment]
Thanks for your comment.
