### ISSUE TITLE
DB Column disappeared in Objective-C with Xcode8.1

### ISSUE THREAD

**Issue by Adonis640320** [martinrybak/SQLClient#35]
Hi, 
Using this SQLClient with iOS on macSierra and Xcode8.1, I've got a problem.
I'm retrieving image data from MSSQL DB, but I can not get the image field.
In other words, the Image field is not in the result of SQLClient query execute.
I can not use the key for image.
Please help.
Best Regards

**Comment by martinrybak** [comment]
Please try the `types` branch. This is the pre-1.0 release and has proper data type conversion.

**Comment by Adonis640320** [comment]
Thanks for your reply. I will try.
