### ISSUE TITLE
Connecting IPV6

### ISSUE THREAD

**Issue by sureshr207** [martinrybak/SQLClient#37]
Hi Martin,
I found this very useful for connecting to SQL Server.
For IPV4 connections, I used
In client connect:@"server:port" - XXX.XXX.XXX.XXX:XXXX & its working perfectly.
I have specific IPV6 address & port for the server & still I am not able to connect the same in IPV6. Also I use freeTDS 1.00.15 & it supports IPV6 too.
Is there something which I need to do or am I missing something?

**Comment by martinrybak** [comment]
Hm, I'm not sure. Are you saying you are able to connect to your database server using FreeTDS directly from a computer on the same network?

**Comment by sureshr207** [comment]
I am able to connect only in my SQL Server using that specific IPV6 address & port.

For IPV6 connections, I tried - client connect:@"server:port" - XXXX:XXXX:X:X::X:XXXX & http://[XXXX:XXXX:X:X::X]:XXXX

Is there any format to specify for IPV6?

Using your repository, I get error - Unable to connect: Adaptive Server is unavailable or does not exist (Severity 9).

**Comment by martinrybak** [comment]
Can you try connecting directly using the FreeTDS binary directly?

**Comment by sureshr207** [comment]
Just installed FreeTDS using Homebrew & checked in terminal. Still I get the same issue in IPV6 whereas IPV4 is working perfectly.

So does this mean I need to change settings in FreeTDS to support IPV6 or I need to check my SQL server?

**Comment by martinrybak** [comment]
Can you confirm which version of FreeTDS you have installed? Looks like you need `v0.95` and above to support IPV6:

http://stackoverflow.com/questions/34883036/remote-connection-to-sql-server-with-freetds-and-ipv6

**Comment by sureshr207** [comment]
There was some server side issue.

client connect:@"server:port" - XXXX:XXXX:X:X::X:XXXX format is working fine now.

Thanks.

**Comment by martinrybak** [comment]
Happy to hear!
