### ISSUE TITLE
Crash on dbloginfree(login)

### ISSUE THREAD

**Issue by Debonairbender** [martinrybak/SQLClient#38]
I am having a strange error while attempting to debug a program that I wrote.  I am running devices with two different iOS versions.  Some are running iOS 7.1.2 and some are running 9.3.5.  The devices running 7.1.2 have no issue whatsoever and function exactly as desired.  The devices running 9.3.5, however, run in to the problem some others have had with the "dbloginfree" line.  I've updated the SQL Client with the most recent updates using CocoaPods still with no success.  The 9.3.5 devices will function as intended about 20% of the time, failing with the error below the other 80%.  Any tips?  Thanks in advance!
![img_20170116_174716 1](https://cloud.githubusercontent.com/assets/25162304/22002851/c995a20c-dc14-11e6-978e-b1f55e63052c.jpg)

**Comment by martinrybak** [comment]
Please try the `types` branch. It has a bunch of fixes.

**Comment by Debonairbender** [comment]
Ah didn't notice that branch, thank you.  Will I be able to just replace the SQLClient.h and SQLClient.m in the types branch over my current ones or is there more I have to do?

**Comment by martinrybak** [comment]
That should be it. Keep in mind that the API changed slightly so you may have to update your consuming code.

**Comment by Debonairbender** [comment]
I am able to compile now after copying over the new SQLClient.m and SQLClient.h as well as linking the new libsysbdb.a, however I am now getting this error.  
![img_20170117_115339 1](https://cloud.githubusercontent.com/assets/25162304/22032869/e0233394-dcab-11e6-8054-46e969df1e99.jpg)

I'm sure this is where I would need to change my code to match the new API, but I am unsure where to start.  Thank you very much for your help, I am pretty new to iOS development and am grateful for you time in assisting me.
