### ISSUE TITLE
20002 Adaptive Server connection failed

### ISSUE THREAD

**Issue by fwaddle** [martinrybak/SQLClient#39]
Hi all,
Anyone else have an issue where the client won't connect and throws the error 'Adaptive Server connection failed'?

I've tried it on several devices and it all works fine except for one iPad. It just so happens that this is the most important device.

I've reset the network settings on the iPad and it still throws the error. It has a SIM card and I've tried using the 4G network, wireless network, and personal hotspot but still throws the same error.

There are no VPN's set or proxy etc...

Any other suggestions?

Thanks,
Mof.

**Comment by fwaddle** [comment]
I worked it out.
Ok so if anyone else comes by this issue here are some of the things I discovered:
1 - check your username / password have no whitespace in them and are correct
2 - check your network connection and that you're not blocked by a firewall

**Comment by martinrybak** [comment]
Good to hear!
