### ISSUE TITLE
result of NULL value is not always correct

### ISSUE THREAD

**Issue by gagaxj** [martinrybak/SQLClient#4]
I noticed an issue which is quite repeatable.

You can just set up a test table like below to repeat the issue.
Let's say a column named myColumn, it is either varchar(5) or decimal(3,1).
Have 3 rows of result. Row1, Row2, Row3.

If All these rows have NULL value of myColumn, the sql query result is fine.
If only Row3 is NULL, it is also fine.
If only Row2 is NULL, while Row1 is not, then there is a Problem. The query result for Row2 is not NULL, instead it uses the value from Row1.

I believe there is something wrong inside the function
- (void)execute:(NSString*)sql completion:(void (^)(NSArray* results))completion

Please fix it, thanks.

**Comment by BenchR267** [comment]
@nhgrif This issue is still not fixed. Did you create your pull request? Was it merged?

**Comment by martinrybak** [comment]
This was fixed in PR #12
