### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by ibolat38** [martinrybak/SQLClient#45]
-- When i try to build project i am getting this error.

ld: '/Users/............./Pods/SQLClient/SQLClient/SQLClient/SQLClient/libfreetds.a(dblib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by martinrybak** [comment]
You must disable bitcode for your target.

**Comment by ibolat38** [comment]
I already did it for pods and projects..
