### ISSUE TITLE
Can't get it working with IOS 10.2 project using cocoa pods method (swift 3.0)

### ISSUE THREAD

**Issue by whencesoever** [martinrybak/SQLClient#46]
I am using xcode Version 8.2.1 and i am trying to write ios 10.2 app. After using cocoa method of

> Open a Terminal window. Update RubyGems by entering: sudo gem update --system. Enter your password when prompted.
> Install CocoaPods by entering sudo gem install cocoapods.
> Create a file at the root of your Xcode project folder called Podfile.
> Enter the following text: pod 'SQLClient', '~> 0.1.3'
> In Terminal navigate to this folder and enter pod install.
> You will see a new SQLClient.xcworkspace file. Open this file in Xcode to work with this project from now on.
> 

 adding sql to my project i can see this error :

ld: '.../Pods/SQLClient/SQLClient/SQLClient/SQLClient/libfreetds.a(dblib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

But changing Enable_bitcode to NO on both projects is not working. 

i also tried: Build Settings > Architectures > "Build Active Architecture Only" to No? 
same result.

**Comment by martinrybak** [comment]
I was able to get it to work on a brand new project iOS 10.2 project in Xcode 8.2.1 by going to Build Settings > Build Options > Enable Bitcode = NO.
