### ISSUE TITLE
Is there any way to connect to azure database the same way?

### ISSUE THREAD

**Issue by whencesoever** [martinrybak/SQLClient#48]
I managed to connect to typical SQL-Server on both local and not local server. But what i want to try to do now is to connect to azure database. Every time i try to do this i get this error:
```
Server name not found in configuration files
Unknown host machine name 
```
Should i specify port differently?

**Comment by whencesoever** [comment]
when i add port with `:1433` instead of `,1433` i got this error:

`Adaptive Server connection failed`

**Comment by martinrybak** [comment]
Looks like you may need to recompile the FreeTDS binary with some additional options: https://martinrichards.tumblr.com/post/28488121620/connecting-to-sql-azure-using-freetds

If you figure it out let me know.
