### ISSUE TITLE
Can not run pod 'SQLClient', '~> 1.0.0'

### ISSUE THREAD

**Issue by kieuquangloc** [martinrybak/SQLClient#52]
@martinrybak I need your help
[!] Unable to satisfy the following requirements:

- `SQLClient (~> 1.0.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SQLClient (~> 1.0.0)`.

**Comment by fuzunspm** [comment]
have the same issue

**Comment by kieuquangloc** [comment]
@fuzunspm you can download the example code, it is using the latest version

**Comment by fuzunspm** [comment]
i'm getting 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SQLClient", referenced from:

```

error after manually import project

**Comment by martinrybak** [comment]
My apologies, version 1.0.0 was not published to Cocoapods correctly. It should be good now.

**Comment by idrises** [comment]
hello I am getting this error in swiftui, how to implement in swiftui
