### ISSUE TITLE
linkedserver support in SQLClient

### ISSUE THREAD

**Issue by param0091** [martinrybak/SQLClient#53]
Hi Martin,

I am developing a cocoa app that is connecting to SQL Server using SQLClient. I need to compare two databases at different instances (checking for updates purpose). I have found "sp_addlinkedserver" method while one using MSSQL but how we can achieve the same using SQLClient. Please suggest.

Also we are facing some issue regarding pdf and image data insertion, according to you it was fixed under 'types' branch but we are unable to find it.

Thanks

**Comment by martinrybak** [comment]
You should be able to invoke it normally, provided you have the permissions to do so:
`EXEC sp_addlinkedserver @server='Servername'`

Please see #56 for how you should be able to insert binary data.
