### ISSUE TITLE
Cocoapod install error

### ISSUE THREAD

**Issue by kieuquangloc** [martinrybak/SQLClient#54]
I created issue at: https://github.com/martinrybak/SQLClient/issues/52

I still can not install SQLClient via cocoapod, could you check it again? @martinrybak 

```
ld: '/MyProject/Pods/SQLClient/SQLClient/SQLClient/SQLClient/libsybdb.a(dblib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This error happens when I uncomment "use_frameworks!" in pod file to use other swift pod project, that pod and SQLCLient are important too, what should I do now?

**Comment by martinrybak** [comment]
You must disable bitcode for your project.
