### ISSUE TITLE
ipv6 - Adaptive Server is unavailable or does not exist” error connecting to SQL Server

### ISSUE THREAD

**Issue by atulgawali** [martinrybak/SQLClient#55]
Hello, 

          On ipv4 network my application working good, But on ipv6 fetching the error **Adaptive Server is unavailable or does not exist” error connecting to SQL Server**.

for ipv6 network is there any changes, please let me know if i missing something.

**Comment by whencesoever** [comment]
I had the same issue. Please try to change connection string little bit. https://www.connectionstrings.com/sql-server/

**Comment by atulgawali** [comment]
Thanks for the reply,

I am fetching  problem in iOS, there is no option to change connection string.

 [client connect:OTP_GD_DB_IP username:OTP_GD_DB_USER_NAME password:OTP_GD_DB_PASSWORD database:@"OTP_DB_NAME" completion:^(BOOL success) {
        if (success)
        {
        }
}

**Comment by martinrybak** [comment]
Please see #37.
