### ISSUE TITLE
Just updated from 0.1.3 to master and getting many errors... 

### ISSUE THREAD

**Issue by pascalfriedrich** [martinrybak/SQLClient#57]
Please see the screenshot...

![image](https://user-images.githubusercontent.com/20318830/37420968-7272ea20-27b8-11e8-83e7-330e3bc2c4ee.png)

**Comment by martinrybak** [comment]
You may have to clean your derived data folder.

**Comment by pascalfriedrich** [comment]
Cleaned Build + derived data without success.

**Comment by martinrybak** [comment]
Try creating a new project with the 1.0.0 version.

**Comment by pascalfriedrich** [comment]
It's working. Why not in my existing project? Argh :(
