### ISSUE TITLE
No Delegate and callbackQueue anymore?

### ISSUE THREAD

**Issue by pascalfriedrich** [martinrybak/SQLClient#58]
It's not possible for me to update from 0.1.3 on an existing project to 1.0.0 via Cocoapods, so I decided to install it manually. After copying the files into the project and importing the header, Xcode tells me that there is no SQLClientDelegate and no callbackQueue property anymore.

Would be great if you could help us to solve these problems...

#57

**Comment by pascalfriedrich** [comment]
...additionally I have trouble to execute some queries successively. It seems to be a timing problem which didn't occur in 0.1.3.
Executing a checksum check followed by a SELECT Statement causing an error (not connected...) for the following statements.
Did you changed something in that way?

Edit: Discovered in the commits, that you removed the delegate and added notificationcenter...

**Comment by martinrybak** [comment]
That is correct, the delegate API was changed in favor of `NSNotificationCenter`. Not sure what is going on with your other issue. Please create another ticket with more detail, thanks.
