### ISSUE TITLE
Receiving incomplete data

### ISSUE THREAD

**Issue by pascalfriedrich** [martinrybak/SQLClient#59]
Sorry for the next issue, but the next problem is here:

With 0.1.3 the output of SELECT  * FROM dbo.V_TOUR; is:

`["mze": "1", "abholung": "0", "tour": "29", "tourname": "Mo. Hopfen [1]", "tournr": "5"]
["mze": "1", "abholung": "1", "tour": "11", "tourname": "Abholer", "tournr": "2"]
["mze": "1", "abholung": "0", "tour": "31", "tourname": "Die. Oberstdorf [1]", "tournr": "6"]
["mze": "1", "abholung": "0", "tour": "105", "tourname": "Lagerumbuchung HV nach Prod.", "tournr": "7777"]
["mze": "1", "abholung": "0", "tour": "17", "tourname": "Lieferung", "tournr": "1"]
["mze": "1", "abholung": "0", "tour": "19", "tourname": "Spedition", "tournr": "3"]
["mze": "1", "abholung": "0", "tour": "107", "tourname": "Lagerumbuchung Prod nach HV", "tournr": "7778", "elb": "ELB Produktion"]`

Printing at the same place with 1.0.0 gives the following output:

`["tourname": "Mo. Hopfen [1]"]
["tourname": "Abholer"]
["tourname": "Die. Oberstdorf [1]"]
["tourname": "Lagerumbuchung HV nach Prod."]
["tourname": "Lieferung"]
["tourname": "Spedition"]
["tourname": "Lagerumbuchung Prod nach HV", "elb": "ELB Produktion"]
`

No matter which Database/View targeting... the same error. Only receiving Strings.

**Comment by martinrybak** [comment]
In 1.0, SQL Server data types are converted to their Objective-C counterparts. Prior to that, everything was returned as `NSString`. Please check your code to make sure you are not still expecting strings.

**Comment by pascalfriedrich** [comment]
Thank you very much! That's it. We expected string. Fixed and everything works like a charm.

**Comment by martinrybak** [comment]
Glad to hear!
