### ISSUE TITLE
GUID not generated correctly

### ISSUE THREAD

**Issue by danmartyn** [martinrybak/SQLClient#61]
Hello,

I'm trying to connect to a server and get some info from a table, where one of the columns is a GUID. When I look at the values in the dictionary, the GUID is not matching with what is in the table when I look at it from running a SQL query in Visual Studio Code. The last 2 portions are correct, but the first 3 portions have the correct values, but are not in the correct order. Any idea what is going on there? This is running on macOS 10.13.4 on a MacBook Pro.

Thanks

**Comment by martinrybak** [comment]
That is due to the Microsoft string representation of a GUID being different than the actual byte order:
https://msdn.microsoft.com/en-us/library/system.guid.tobytearray.aspx?f=255&MSPPError=-2147217396

**Comment by danmartyn** [comment]
Does that mean there's no way to get the same representation as what's stored in the DB?
