### ISSUE TITLE
how can I get results on message notification?

### ISSUE THREAD

**Issue by oes01** [martinrybak/SQLClient#69]
I want to get results on message notification?
- (void)message:(NSNotification*)notification
{
//instead 
  NSString* message = notification.userInfo[SQLClientMessageKey];
//like this
 NSArray* results = notification.userInfo[ -- how can I do that ? -- ];

}

**Comment by martinrybak** [comment]
Notifications are only for errors and messages. To get the query results you have to pass a `completion` handler to the `execute` method. See the readme.
