### ISSUE TITLE
Publish to App Store

### ISSUE THREAD

**Issue by hesseflores** [martinrybak/SQLClient#70]
everything works correctly but when I try to publish the application, apple rejects it as if there was no connection

**Comment by martinrybak** [comment]
You'll have to give me a little more to work with.

**Comment by hesseflores** [comment]
Thank you for responding, I can send you the crashlog that they gave me previously, now I only handle the error with a personalized message indicating problem with the connection but in the same way I was rejected.

[https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple124/v4/23/3d/5a/233d5a9a-3e9a-7250-27b5-0d52a0270cef/attachment-408552745504013686crashlog-4DF3CB42-4FA3-4C59-8FE4-DE3E37235C7C.txt?accessKey=1559906878_1814048116174485340_z5P%2FatkMkkfGY7txn8Q%2F%2BBdCaoJkXN8yoUB0MJYBbczIjY271r7lQTB8k%2BOLXWvBJzYPzjb29CHMkWHKi0dHLp6RMzIVGaafbvekN3Q%2Bp64zpOpMI4sssVc1c%2F5GguafuolOn0KPNHe2cDqAWxseq0GOt%2FyMdDECTzDUX3fqxrmi%2FLr31zLiMsqN%2FJ%2FMgGawB2w0nqLlqj0804S9ie0j5XiUc7R81oVvkuEu7pIIuOFPPA6k4rI1kQsdOS%2FXK%2FjO](url)

[https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple114/v4/2e/e3/0c/2ee30cba-fb5f-db24-2df6-68e65a985e50/attachment-5331524902286897395crashlog-E896BB57-1C0C-406A-A65A-F20D242E27A8.txt?accessKey=1559906878_2428823978172204795_bWSb%2B5qr6HxyqMm3tvpK76hTCaTyz81jllxdsGfFp8jdli6UZ%2BNvVs%2F%2FFM1c%2BBUGEUx73I5AErT3CpwD9Cdw5JV0cTXxL7SLEMnCd4P9nKuxmb8QZ79rgplZLs%2FLLAWaLZ1e%2B1tIEWjWk2H60JlG7JntsCHMgHjjMp3OSTwQpnBzquL%2By2f3Ihx23QEi%2BfMvgYH9BBixsrNA%2FfYoLJc4EEfkMe5y3fxWTAnK5tRzzdv8fgHVwvCVmzTD%2F%2FCkrwhn](url)

[https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple114/v4/60/f4/48/60f44861-6477-04c5-1fdd-49f002a1dee2/attachment-4979550593624252810crashlog-5D415351-5415-46BA-98E7-3560689FB4A7.txt?accessKey=1559906878_6087472642249752161_Die9hOa5RHCIVPdKeRwphwk295TLwxpMp1toqY%2Be6FxmZuzi6f3Wqrcdz3R4tmq0Oe0Ma%2B6nZEVOauZd3aTtPqxJgmGnZ6IYt0Yd%2F0ZIjiaIHZ%2B%2BXDGVMIgLgld6lQpPkvuaMpo21oQ3cmYLHus8Y5RlnJdywDo%2BUpr2oRBTfL1N1p4QxJLZeTTuvXjCeS4S%2FZskbADfD4bENjZTft%2FxS5f3itVl6J0MC38Lu6CixK5OQtNDW0lVnRIVPf935hYj](url)

**Comment by martinrybak** [comment]
Can you symbolicate those crash reports?

**Comment by hesseflores** [comment]
I do not know how to do that, I'm developing the app with a simulator, I think I need a physical device to use that option in xcode

**Comment by martinrybak** [comment]
https://developer.apple.com/library/archive/technotes/tn2151/_index.html#//apple_ref/doc/uid/DTS40008184-CH1-SYMBOLICATION

**Comment by hesseflores** [comment]
Thanks, he says "no dSYMs were found ..." and "no crash logs ..." I think it's because it's been over 2 weeks since the rejection. The only way I get the same error is when I disconnect the internet and try to use my application, you think it has to do with the server that I'm connecting to that does not have ssl or something similar that they have some firewall blocking perform the tests. I will now try to test with a network only ipv6 to see if it also works for me even though they do not specify me that this network was the problem
