### ISSUE TITLE
Crash with the login variable

### ISSUE THREAD

**Issue by chiscoso** [martinrybak/SQLClient#9]
I have an app that executes a query every 5 seconds, at some point of executing a query it crashes by a “bad access error” in the methods connection failure and connection success, it appears that at some point the login variable gets freed and the bad access exception is thrown crashing my app. I haven’t been able to track this error to a possible fix.
Another thing to mention, is that this happens on the iOS simulator, i have not been able to test the app in a real device.

Hope the image looks well, and help with the issue.

![image](https://f.cloud.github.com/assets/6809408/2287885/a1b73540-9ff2-11e3-938b-fedae85e2a88.png)

**Comment by martinrybak** [comment]
This issue has been fixed on the `types` branch.
